revert whitespace changes

diff --git a/scripts/create-product-ipk b/scripts/create-product-ipk
--- a/scripts/create-product-ipk
+++ b/scripts/create-product-ipk
@@ -27,19 +27,19 @@ eval set -- "$opts"
 while :; do
     arg="$1"; shift
     case "$arg" in
-    (--help | -h)
-        cat <<EOF
+	(--help | -h)
+	    cat <<EOF
 Usage: $this [options]
 
 Create an IPK file for installing SoundTouch with opkg.
 
 Options:
 EOF
-        exit 0
-        ;;
+	    exit 0
+	    ;;
 
-    (--) break ;;
-    (*)  echo >&2 "$this: internal error at '$arg'"; exit 1 ;;
+	(--) break ;;
+	(*)  echo >&2 "$this: internal error at '$arg'"; exit 1 ;;
     esac
 done
 
