Fail if required packages are not installed

diff --git a/scripts/create-product-ipk b/scripts/create-product-ipk
--- a/scripts/create-product-ipk
+++ b/scripts/create-product-ipk
@@ -155,7 +155,12 @@ EOF
 
 # Generate the Open Source license list from the Riviera-HSP-licenses.tar.gz file 
 # Note that for PGC we need to add the -soundbar option when invoking the Perl script
-"$wspace/OpenSourceLicensing/riviera-licenses" "$riviera_hsp_images_dir/Riviera-HSP-licenses.tar.gz" "$opt_dir/html/licenses"
+if dpkg -l libfile-slurp-perl >& /dev/null && dpkg -l libdigest-md5-file-perl >& /dev/null; then
+    "$wspace/OpenSourceLicensing/riviera-licenses" "$riviera_hsp_images_dir/Riviera-HSP-licenses.tar.gz" "$opt_dir/html/licenses"
+else
+   echo "Error: please run 'sudo apt install libfile-slurp-perl libdigest-md5-file-perl' to support open source license generation"
+   exit 1
+fi
 
 # Copy public keys in FS for development key. EC will take care of generation for Production 
 secure_dir=$opt_dir/etc/secure/
