Cherry-pick a3986e0474ba162520ace4ca0aded54b7ce2ddd7 from Eddie

diff --git a/scripts/create-hsp-ipk b/scripts/create-hsp-ipk
--- a/scripts/create-hsp-ipk
+++ b/scripts/create-hsp-ipk
@@ -61,6 +61,7 @@ here=$(cd "$(dirname $0)" && echo "$PWD") || exit
 wspace=$(cd "$here/.." && echo "$PWD") || exit
 
 riviera_hsp_images_dir=$(components get Riviera-HSP-Images installed_location) || exit
+swup_dir=$(components get SoftwareUpdate-qc8017_32 installed_location) || exit
 riviera_hsp_ver=$(components get Riviera-HSP-Images selected_version) || exit
 riviera_hsp_ver=${riviera_hsp_ver##*/}
 
@@ -82,6 +83,14 @@ echo "Package version \"$riviera_hsp_ver\""
 # update_block.zip is HSP update with using "dd" or blocked update
 # update_block_kernel.zip is HSP update with only kernel update. - THIS SHOULDN'T BE USED except SOS.
 cp "$riviera_hsp_images_dir"/update_block.zip "$opt_dir/hsp/update_ext4.zip" || exit
+
+# To mark HSP update is in progress fetch the file path from CommonHeader.h file
+hsp_update_indication=`cat "$swup_dir"/include/CommonHeader.h | awk '$3 == "g_HSPUpdateInProgress" {print $5}' | tr -d ';\"'` || exit
+# check if the file name is present or not, error out if file name not found
+if [ -z "$hsp_update_indication" ]; then
+    echo "$this : Error fetching hsp update in progress file name from include/CommonHeader.h"
+    exit 1
+fi
 
 PackageName=hsp
 
@@ -155,6 +164,10 @@ fi
 mkdir -p /cache/recovery/ || exiterror
 echo "--update_package=/opt/Bose/hsp/update_ext4.zip" > /cache/recovery/command || exiterror
 echo "--idle_after" >> /cache/recovery/command || exiterror
+
+# CASTLE-23165 this file will mark that hsp installation is started in recovery mode
+touch $hsp_update_indication || exiterror
+
 # Set Progress End
 /opt/Bose/bin/ProgressReport -n $PackageName -e 0 -i 1 -r RECOVERY -b 0 -p 100
 exit 0
