address review comments

diff --git a/scripts/create-recovery-ipk b/scripts/create-recovery-ipk
--- a/scripts/create-recovery-ipk
+++ b/scripts/create-recovery-ipk
@@ -13,22 +13,43 @@ this=${0##*/} # this script's name
 cfg=Release
 
 tryhelp () {
-    echo "Usage $this -p <product-type>"
-    echo ""
-    echo "Create recovery package for given product type."
+    echo >&2 "Try '$this --help' for more information."
     exit 1
 }
-while getopts ":p:" param; do
-    case "${param}" in
-        p)
-            product_type=${OPTARG}
+opts=$(getopt --name "$this" --shell sh \
+    -o hp: \
+    -l "help,product:" \
+    -- "$@") || tryhelp
+eval set -- "$opts"
+while :; do
+    arg="$1"; shift
+    case "$arg" in
+        (--help | -h)
+            cat << EOF
+Usage: $this [options]
+
+echo "Create recovery package for given product type."
+Options:
+    -p <Product Type e.g. eddie / professor / flipper / taylor> - Product type to use
+    -h - Print help
+EOF
+            exit 0
             ;;
-        *)
-            tryhelp
+        (--) break ;;
+        (--product | -p)
+            product_type="$1"; shift
+            ;;
+        (*) echo >&2 "$this: internal error at '$arg'"; exit 1 ;;
     esac
 done
-shift $((OPTIND-1))
-if [ -z "${product_type}" ]; then
+
+if (( $# != 0 )); then
+    echo >&2 "$this: unexpected argument '$1'"
+    tryhelp
+fi
+if [ -z "$product_type" ]
+then
+    echo >&2 "$this: -p or --product is mandatory argument"
     tryhelp
 fi
 
