Convert to use AudioSource-Spotify

diff --git a/scripts/create-product-ipk b/scripts/create-product-ipk
--- a/scripts/create-product-ipk
+++ b/scripts/create-product-ipk
@@ -27,19 +27,19 @@ eval set -- "$opts"
 while :; do
     arg="$1"; shift
     case "$arg" in
-	(--help | -h)
-	    cat <<EOF
+    (--help | -h)
+        cat <<EOF
 Usage: $this [options]
 
 Create an IPK file for installing SoundTouch with opkg.
 
 Options:
 EOF
-	    exit 0
-	    ;;
+        exit 0
+        ;;
 
-	(--) break ;;
-	(*)  echo >&2 "$this: internal error at '$arg'"; exit 1 ;;
+    (--) break ;;
+    (*)  echo >&2 "$this: internal error at '$arg'"; exit 1 ;;
     esac
 done
 
@@ -69,9 +69,13 @@ audiopath64_dir=$(components get AudioPathService-qc8017_64 installed_location) 
 audiopathproduct64_dir=$(components get AudioPathProducts-qc8017_64 installed_location) || exit
 audiosource_upnp_dir=$(components get AudioSource-UPnP-qc8017_32 installed_location) || exit
 audiosource_bmx_dir=$(components get AudioSource-BMX-qc8017_32 installed_location) || exit
+audiosource_spotify_dir=$(components get AudioSource-Spotify-qc8017_32 installed_location) || exit
 castlenetworkservice_dir=$(components get NetworkService-qc8017_32 installed_location) || exit
 castlesass_dir=$(components get SASS-qc8017_64 installed_location) || exit
 castlepassport_dir=$(components get Passport-qc8017_32 installed_location) || exit
+networkservice_dir=$(components get NetworkService-qc8017_32 installed_location) || exit
+sass_dir=$(components get SASS-qc8017_64 installed_location) || exit
+passport_dir=$(components get Passport-qc8017_32 installed_location) || exit
 wifi_setup_webpage_dir=$(components get bose-web-riviera-ap-page installed_location) || exit
 web_update_page_dir=$(components get bose-web-update-page installed_location) || exit
 lpmservice_dir=$(components get RivieraLpmService-qc8017_32 installed_location) || exit
@@ -142,7 +146,6 @@ cp "$stfs"/opt/Bose/AudioNotification "$opt_dir/bin" || exit
 cp "$stfs"/opt/Bose/Deezer "$opt_dir/bin" || exit
 cp "$stfs"/opt/Bose/IHeart "$opt_dir/bin" || exit
 cp "$stfs"/opt/Bose/SiriusXM "$opt_dir/bin" || exit
-cp "$stfs"/opt/Bose/Spotify "$opt_dir/bin" || exit
 cp -a "$stfs"/opt/Bose/lib "$opt_dir" || exit
 cp -a "$stfs"/var/lib/iot "$opt_dir" || exit
 # ----------------------------------------------------------------------------
@@ -251,6 +254,7 @@ mkdir -p "$opt_dir/etc/ginger-cheevers" || exit
 "$svc_pts_log_decrypt_dir/stage" "$opt_dir" || exit
 "$audiosource_upnp_dir/stage" "$opt_dir" || exit
 "$audiosource_bmx_dir/stage" "$opt_dir" || exit
+"$audiosource_spotify_dir/stage" "$opt_dir" || exit
 "$vm_dir/stage" "$opt_dir" || exit
 "$rcs_dir/stage" "$opt_dir" || exit
 "$devicecontroller_dir/stage" "$opt_dir" || exit
@@ -344,7 +348,7 @@ else
 fi
 # Start Progress
 if [ -f /opt/Bose/bin/ProgressReport ]; then
-	/opt/Bose/bin/ProgressReport -n $PackageName -e 0 -i 0 -r LPM -b 0 -p 1
+    /opt/Bose/bin/ProgressReport -n $PackageName -e 0 -i 0 -r LPM -b 0 -p 1
 fi
 
 exit 0
